name: RPSvAI2
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - scikit-learn
  - edfio
  - matplotlib
  - scipy
  - pandas
  - yaml
